volumes:
  pg_data:

services:
  db:
    image: postgres:latest
    container_name: TronWallet-DB
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
